# Basic
hostname    : ~
config      : ~
arch        : "hvi_cidnet"
model       : "hvi_cidnet"
data        : ~
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : ~
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 1000
steps       : ~
imgsz       : 256
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
keep_subdirs: False
use_fullname: False
exist_ok    : True
verbose     : True

# Model
gated2: True
alpha : 0.8

# Data
data_train_lol_blur        : "data/enhance/lol_blur/train"
data_train_lol_v1          : "data/enhance/lol_v1/train"
data_train_lol_v2_real     : "data/enhance/lol_v2_real/train"
data_train_lol_v2_synthetic: "data/enhance/lol_v2_synthetic/train"
data_train_sid             : "data/enhance/sid/train"
data_train_sice            : "data/enhance/sice/train"

data_val_lol_blur          : "data/enhance/lol_blur/test/lq"
data_val_lol_v1            : "data/enhance/lol_v1/test/lq"
data_val_lol_v2_real       : "data/enhance/lol_v2_real/test/lq"
data_val_lol_v2_synthetic  : "data/enhance/lol_v2_synthetic/test/lq"
data_val_sid               : "data/enhance/sid/test/lq"
data_val_sice              : "data/enhance/sice/test/lq"

data_valgt_lol_blur        : "data/enhance/lol_blur/test/hq"
data_valgt_lol_v1          : "data/enhance/lol_v1/test/hq"
data_valgt_lol_v2_real     : "data/enhance/lol_v2_real/test/hq"
data_valgt_lol_v2_synthetic: "data/enhance/lol_v2_synthetic/test/hq"
data_valgt_sid             : "data/enhance/sid/test/hq"
data_valgt_sice            : "data/enhance/sice/test/hq"

lol_blur          : False
lol_v1            : False
lol_v2_real       : False
lol_v2_synthetic  : False
sid               : False
sice              : False

# Training
batch_size        : 8
crop_size         : 256
start_epoch       : 0
lr                : 0.0001
gpu_mode          : True
threads           : 16
cos_restart_cyclic: False
cos_restart       : True
warmup_epochs     : 3
start_warmup      : True

HVI_weight        : 1.0
L1_weight         : 1.0
D_weight          : 0.5
E_weight          : 50.0
P_weight          : 0.01
