# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "uretinexnet++"                                                   # Model architecture or family (e.g., resnet).
model       : &model "uretinexnet++"                                            # Model name (e.g., resnet50).
data        : &data "lol_v1"                                                    # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "uretinexnet++_lol_v1"                                  # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/enhance/llie/uretinexnet++/uretinexnet++/lol_v1" # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 0                                                                 # Random seed.
imgsz       : &imgsz 512                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 200                                                       # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Datamodule
datamodule:
  name      : *data                                                             # Data module name (e.g., cifar10).
  root      : "data/enhance/lol_v1"                                             # Root directory of the dataset.
  transform : ~
  to_tensor : True                                                              # If ``True``, convert the data to tensor.
  batch_size: 1                                                                 # Batch size.
  cache_data: False                                                             # If ``True``, cache the data.
  shuffle   : True                                                              # If ``True``, shuffle the data.
  verbose   : *verbose                                                          # Verbosity.

# Misc
decom_model_high_weights  : "vision/enhance/llie/uretinexnet++/uretinexnet++/lol_v1/uretinexnet++_lol_v1_decom_high_light.pth"
decom_model_low_weights   : "vision/enhance/llie/uretinexnet++/uretinexnet++/lol_v1/uretinexnet++_lol_v1_decom_low_light.pth"
fusion_weights            : "vision/enhance/llie/uretinexnet++/uretinexnet++/lol_v1/uretinexnet++_lol_v1_fusion.pth"
pretrain_unfolding_weights: "vision/enhance/llie/uretinexnet++/uretinexnet++/lol_v1/uretinexnet++_lol_v1_unfolding.pth"
ratio: 3
