# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "colie"                                                           # Model architecture or family (e.g., resnet).
model       : &model "colie_re"                                                 # Model name (e.g., resnet50).
data        : &data ~                                                           # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "colie_re"                                              # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights ~                                                        # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 0                                                                 # Random seed.
imgsz       : &imgsz 256                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 100                                                       # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.
                                                                                
# Network
network: &network                                                               # Network architecture.
  window_size : 7                                                               # Context window size.
  down_size   : *imgsz                                                          # Downsampling size.
  num_layers  : 4                                                               # Number of layers.
  hidden_dim  : 256                                                             # Hidden dimension.
  add_layer   : 2                                                               # Addition layer.
  weight_decay: [0.1, 0.0001, 0.001]
  iters       : *epochs

# Optimizer
optimizer: &optimizer                                                           # Optimizer(s).
  optimizer:
    name        : "adam"
    lr          : 0.00001
    weight_decay: 0.0003
  lr_scheduler       : ~                                                        # Learning rate scheduler.s
  network_params_only: True

# Loss
loss: &loss                                                                     # Loss function.
  L    : 0.3                                                                    # L parameter.
  alpha: 1                                                                      # Fidelity control.
  beta : 20                                                                     # Illumination smoothness.
  gamma: 8                                                                      # Exposure control.
  delta: 5                                                                      # Sparsity level.

# Metric
metrics: &metrics                                                               # Metrics for evaluation.
  train: ~
  val  :
    - {name: "psnr"}
    - {name: "ssim"}
  test :
    - {name: "psnr"}
    - {name: "ssim"}

# Model
modelmodule:
  name     : *model                                                             # Model name (e.g., resnet50).
  root     : *save_dir                                                          # Root directory of the current run.
  fullname : *fullname                                                          # Full name of the current run (e.g., resnet50_cifar10_01).
  <<       : *network                                                           # Network architecture.
  weights  : *weights                                                           # Path to the pretrained weights.
  optimizer: *optimizer                                                         # Optimizer(s).
  loss     : *loss                                                              # Loss function.
  metrics  : *metrics                                                           # Metrics for evaluation.
  debug    : *save_debug                                                        
  verbose  : *verbose                                                           # Verbosity.

# Datamodule
datamodule:
  name      : *data                                                             # Data module name (e.g., cifar10).
  root      : "data/"                                                           # Root directory of the dataset.
  transform : ~                                                                 # Data augmentation.
  to_tensor : True                                                              # If ``True``, convert the data to tensor.
  batch_size: 1                                                                 # Batch size.
  cache_data: False                                                             # If ``True``, cache the data.
  shuffle   : True                                                              # If ``True``, shuffle the data.
  verbose   : *verbose                                                          # Verbosity.

# Trainer
trainer:
  accelerator: "auto"                                                           # Accelerator.
  callbacks:
    - {name: "model_checkpoint", filename: *fullname, monitor: "val/psnr", mode: "max"}
    - {name: "model_checkpoint", filename: *fullname, monitor: "val/ssim", mode: "max", save_last: True}
    - {name: "log_training_progress", "filename": "log.csv", "every_n_epochs": 1, verbose: *verbose}
    - {name: "learning_rate_monitor"}
    - {name: "rich_model_summary", max_depth: 2}
    - {name: "rich_progress_bar", refresh_rate: 1, leave: False}
  check_val_every_n_epoch: 1                                                    # Run validation loop every after every `n` training epochs.
  default_root_dir       : *save_dir                                            # Default path for logs and weights.
  devices                : "auto"                                               # Will be mapped to either `gpus`, `tpu_cores`, `num_processes` or `ipus`.
  enable_checkpointing   : True                                                 
  enable_model_summary   : True                                                 
  enable_progress_bar    : True                                                 
  log_every_n_steps      : 1                                                    # How often to log within steps.
  logger                 : True                                                 # Logger (or iterable collection of loggers) for experiment tracking (True = `TensorBoardLogger`).
  max_epochs             : *epochs                                              # -1: infinite training.
  max_steps              : *steps                                               # -1: infinite training.
  precision              : 32                                                   # Double precision (64), full precision (32), half precision (16) or bfloat16 precision (bf16).
  strategy               : "auto"                                               # 'ddp', 'ddp_spawn', 'ddp2', 'ddp_cpu', 'ddp2_cpu', 'ddp_spawn_cpu', 'horovod', 'tpu', 'tpu_spawn', 'auto'.
