# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "depth_anything_v2"                                               # Model architecture or family (e.g., resnet).
model       : &model "depth_anything_v2_vitl"                                   # Model name (e.g., resnet50).
data        : &data "da_2k"                                                     # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "depth_anything_v2_vitl_da_2k"                          # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/types/depth/depth_anything_v2/depth_anything_v2_vitl/da_2k/depth_anything_v2_vitl_da_2k.pth" # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 2                                                                 # Random seed.
imgsz       : &imgsz 518                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 200                                                       # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Network
network: &network                                                               # Network architecture.
  encoder     : "vitl"
  features    : 256
  out_channels: [256, 512, 1024, 1024]
  pred_only   : True
  format      : 2  # 0: grayscale, 1: color, 2: both

# Model-module (Note: I want to name this `model`, but it conflicts with the `model` key in the basic section)
modelmodule:
  name     : *model                                                             # Model name (e.g., resnet50).
  root     : *save_dir                                                          # Root directory of the current run.
  fullname : *fullname                                                          # Full name of the current run (e.g., resnet50_cifar10_01).
  <<       : *network                                                           # Network architecture.
  weights  : *weights                                                           # Path to the pretrained weights.
  optimizer: ~                                                                  # Optimizer(s).
  loss     : ~                                                                  # Loss function.
  metrics  : ~                                                                  # Metrics for evaluation.
  debug    : *save_debug
  verbose  : *verbose                                                           # Verbosity.
