# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "hinet"                                                           # Model architecture or family (e.g., resnet).
model       : &model "hinet_re"                                                 # Model name (e.g., resnet50).
data        : &data "rain13k"                                                   # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "hinet_re_rain13k"                                      # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/enhance/multitask/hinet/hinet_re/rain13k/hinet_re_rain13k.pt" # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 100                                                               # Random seed.
imgsz       : &imgsz 256                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 200                                                       # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

### For ``mon`` Framework ###
# Network
network: &network                                                               # Network architecture.
  num_channels: 64
  depth       : 5
  relu_slope  : 0.2
  in_pos_left : 0
  in_pos_right: 4
  
# Optimizer
optimizer: &optimizer                                                           # Optimizer(s).
  - optimizer:
      name        : "adam"
      lr          : 0.0002
      weight_decay: 0
    lr_scheduler       :                                                        # Learning rate scheduler.
      scheduler:
        name      : "cosine_annealing_lr"
        T_max     : 400000
        eta_min   : 0.0000001
        last_epoch: -1
      interval : "epoch"
      frequency: 1
      monitor  : "train/loss"
      strict   : True
      name     : None
    network_params_only: True
    
# Loss
loss: &loss                                                                     # Loss function.
  name: "psnr_loss"
  to_y: True

# Metric
metrics: &metrics                                                               # Metrics for evaluation.
  train: ~
  val  :
    - {name: "psnr"}
    - {name: "ssim"}
  test :
    - {name: "psnr"}
    - {name: "ssim"}
    
# Model-module (Note: I want to name this `model`, but it conflicts with the `model` key in the basic section)
modelmodule:
  name     : *model                                                             # Model name (e.g., resnet50).
  root     : *save_dir                                                          # Root directory of the current run.
  fullname : *fullname                                                          # Full name of the current run (e.g., resnet50_cifar10_01).
  <<       : *network                                                           # Network architecture.
  weights  : *weights                                                           # Path to the pretrained weights.
  optimizer: *optimizer                                                         # Optimizer(s).
  loss     : *loss                                                              # Loss function.
  metrics  : *metrics                                                           # Metrics for evaluation.
  debug    : *save_debug                                                        
  verbose  : *verbose                                                           # Verbosity.

# Datamodule
datamodule:
  name      : *data                                                             # Data module name (e.g., cifar10).
  root      : "data/enhance/sice_me"                                            # Root directory of the dataset.
  transform :                                                                   # Data augmentation.
    - {name: "resize", height: *imgsz, width : *imgsz}
    - {name: "flip"}
    - {name: "rotate"}
  to_tensor : True                                                              # If ``True``, convert the data to tensor.
  batch_size: 32                                                                # Batch size.
  cache_data: False                                                             # If ``True``, cache the data.
  shuffle   : True                                                              # If ``True``, shuffle the data.
  verbose   : *verbose                                                          # Verbosity.
  
# Trainer
trainer:
  accelerator: "auto"                                                           # Accelerator.
  callbacks:
    - {name: "model_checkpoint", filename: *fullname, monitor: "val/psnr", mode: "max"}
    - {name: "model_checkpoint", filename: *fullname, monitor: "val/ssim", mode: "max", save_last: True}
    - {name: "log_training_progress", "filename": "log.csv", "every_n_epochs": 1, verbose: *verbose}
    - {name: "learning_rate_monitor"}
    - {name: "rich_model_summary", max_depth: 2}
    - {name: "rich_progress_bar", refresh_rate: 1, leave: False}
  check_val_every_n_epoch: 1                                                    # Run validation loop every after every `n` training epochs.
  default_root_dir       : *save_dir                                            # Default path for logs and weights.
  devices                : "auto"                                               # Will be mapped to either `gpus`, `tpu_cores`, `num_processes` or `ipus`.
  enable_checkpointing   : True                                                 
  enable_model_summary   : True                                                 
  enable_progress_bar    : True
  gradient_clip_val      : 0.01                                                 # 0: no clipping.
  log_every_n_steps      : 1                                                    # How often to log within steps.
  logger                 : True                                                 # Logger (or iterable collection of loggers) for experiment tracking (True = `TensorBoardLogger`).
  max_epochs             : *epochs                                              # -1: infinite training.
  max_steps              : *steps                                               # -1: infinite training.
  precision              : 32                                                   # Double precision (64), full precision (32), half precision (16) or bfloat16 precision (bf16).
  strategy               : "auto"                                               # 'ddp', 'ddp_spawn', 'ddp2', 'ddp_cpu', 'ddp2_cpu', 'ddp_spawn_cpu', 'horovod', 'tpu', 'tpu_spawn', 'auto'.
