# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "hvi_cidnet"                                                      # Model architecture or family (e.g., resnet).
model       : &model "hvi_cidnet"                                               # Model name (e.g., resnet50).
data        : &data "sice"                                                      # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "hvi_cidnet_sice"                                       # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/enhance/llie/hvi_cidnet/hvi_cidnet/sice/hvi_cidnet_sice.pth" # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : [1, 1000000]                                                      # Random seed.
imgsz       : &imgsz 256                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 1000                                                      # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Network
network: &network                                                               # Network architecture.
  gated      : True
  gated2     : False
  alpha      : 0.8
  gamma      : 1.0
  start_gamma: 60
  end_gamma  : 120

# Optimizer
optimizer: &optimizer                                                           # Optimizer(s).
  lr                : 0.0001
  cos_restart_cyclic: False
  cos_restart       : True

# Loss
loss: &loss                                                                     # Loss function.
  HVI_weight: 1.0
  L1_weight : 1.0
  D_weight  : 0.5
  E_weight  : 50.0
  P_weight  : 0.01

# Datamodule
datamodule:
  name      : *data                                                             # Data module name (e.g., cifar10).
  root      : "data/enhance/sice"                                               # Root directory of the dataset.
  transform :                                                                   # Data augmentation.
    - {name: "random_crop", height: *imgsz, width: *imgsz}
    - {name: "horizontal_flip"}
    - {name: "vertical_flip"}
  to_tensor : True                                                              # If ``True``, convert the data to tensor.
  batch_size: 8                                                                 # Batch size.
  cache_data: False                                                             # If ``True``, cache the data.
  shuffle   : True                                                              # If ``True``, shuffle the data.
  verbose   : *verbose                                                          # Verbosity.

# Trainer
trainer:
  warmup_epochs: 3
  start_warmup : True
  grad_detect  : False
  grad_clip    : True
  norm_size    : True
