# Basic
hostname    : ~
config      : ~
arch        : "airnet"
model       : "airnet"
data        : ~
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : ~
save_dir    : ~
weights     : "zoo/vision/enhance/multitask/airnet/airnet/pretrained/airnet_dehaze.pth"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 200
steps       : ~
imgsz       : 518
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
keep_subdirs: False
use_fullname: False
exist_ok    : True
verbose     : True

# Misc
mode        : 2  # 0 for denoise, 1 for derain, 2 for dehaze, 3 for all-in-one
batch_size  : 1
