# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "esdnet_snn"                                                      # Model architecture or family (e.g., resnet).
model       : &model "esdnet_snn"                                               # Model name (e.g., resnet50).
data        : &data "rain13k"                                                   # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "esdnet_snn_rain13k"                                    # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/enhance/derain/esdnet_snn/esdnet_snn/rain13k/esdnet_snn_rain13k.pt"  # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 100                                                               # Random seed.
imgsz       : &imgsz 512                                                        # Image size for the model.
resize      : True                                                              # Resize the input image to `imgsz`.
epochs      : &epochs 1000                                                      # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug False                                                 # Save the debug information.
use_fullname: False                                                             # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Network
network: &network                                                               # Network architecture.
  mode: "ESDNet3"

# Optimizer
optimizer: &optimizer                                                           # Optimizer(s).
  lr           : 0.0001
  min_lr       : 0.0000001
  warmup_epochs: 3

# Datamodule
datamodule:
  name            : *data                                                       # Data module name (e.g., cifar10).
  root            : "data/enhance/rain13k"                                      # Root directory of the dataset.
  transform       : ~                                                           # Data augmentation.
  to_tensor       : True                                                        # If ``True``, convert the data to tensor.
  batch_size      : 16                                                          # Batch size.
  patch_size_train: 64
  patch_size_test : 64
  cache_data      : False                                                       # If ``True``, cache the data.
  shuffle         : True                                                        # If ``True``, shuffle the data.
  verbose         : *verbose                                                    # Verbosity.

# Trainer
trainer:
  clip_grad: 1.0
  use_amp  : False
