# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "depth_pro"                                                       # Model architecture or family (e.g., resnet).
model       : &model "depth_pro"                                                # Model name (e.g., resnet50).
data        : &data ~                                                           # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "depth_pro"                                             # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/types/depth/depth_pro/depth_pro/pretrained/depth_pro.pt" # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 0                                                                 # Random seed.
imgsz       : &imgsz 512                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs ~                                                         # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Network
network: &network
  patch_encoder_preset: "dinov2l16_384"
  image_encoder_preset: "dinov2l16_384"
  decoder_features    : 256
  use_fov_head        : True
  fov_encoder_preset  : "dinov2l16_384"
  format              : 2                                                       # 0: grayscale, 1: color, 2: both

# Model-module (Note: I want to name this `model`, but it conflicts with the `model` key in the basic section)
modelmodule:
  name     : *model                                                             # Model name (e.g., resnet50).
  root     : *save_dir                                                          # Root directory of the current run.
  fullname : *fullname                                                          # Full name of the current run (e.g., resnet50_cifar10_01).
  <<       : *network                                                           # Network architecture.
  weights  : *weights                                                           # Path to the pretrained weights.
  optimizer: ~                                                                  # Optimizer(s).
  loss     : ~                                                                  # Loss function.
  metrics  : ~                                                                  # Metrics for evaluation.
  debug    : *save_debug
  verbose  : *verbose                                                           # Verbosity.
