# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "retinexformer"                                                   # Model architecture or family (e.g., resnet).
model       : &model "retinexformer"                                            # Model name (e.g., resnet50).
data        : &data "sdsd_outdoor"                                              # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "retinexformer_sdsd_outdoor"                            # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/enhance/llie/retinexformer/retinexformer/sdsd_outdoor/retinexformer_sdsd_outdoor.pth" # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 0                                                                 # Random seed.
imgsz       : &imgsz 512                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs ~                                                         # Training epochs.
steps       : &steps 300000                                                     # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Misc
opt_path: "sdsd_outdoor.yaml"
