#### general settings
name    : neurop_init
is_init : true
is_train: true
device  : cuda

#### datasets
datasets:
  name      : fivek_init
  mode      : init
  dataroot  : fivek_init
  n_cpus    : 8
  batch_size: 1

#### network structures
network_G:
  init_model : ~
  in_nc      : 3
  out_nc     : 3
  base_nf    : 64
  cond_nf    : 32
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G       : !!float 5e-5
  beta1      : 0.9
  beta2      : 0.99
  niter      : 100000
  manual_seed: 0

#### logger
logger:
  print_freq: 100  
