# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "colie"                                                           # Model architecture or family (e.g., resnet).
model       : &model "colie"                                                    # Model name (e.g., resnet50).
data        : &data ~                                                           # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "colie"                                                 # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights ~                                                        # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 0                                                                 # Random seed.
imgsz       : &imgsz 256                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 100                                                       # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Network
network: &network                                                               # Network architecture.
  window    : 7
  num_layers: 4
  hidden_dim: *imgsz
  add_layer : 2
  
# Optimizer
optimizer: &optimizer                                                           # Optimizer(s).
  lr          : 0.00001
  weight_decay: 0.0003

# Loss
loss: &loss                                                                     # Loss function.
  L     : 0.3                                                                   # The "optimally-intense threshold", lower values produce brighter images. Default is ``0.3``.
  alpha : 1                                                                     # Fidelity control. Default is ``1``.
  beta  : 20                                                                    # Illumination smoothness. Default is ``20``.
  gamma : 8                                                                     # Exposure control. Default is ``8``.
  delta : 5                                                                     # Sparsity level. Default is ``5``.
