# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "zero_ig"                                                         # Model architecture or family (e.g., resnet).
model       : &model "zero_ig"                                                  # Model name (e.g., resnet50).
data        : &data ~                                                           # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "zero_ig"                                               # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights "zoo/vision/enhance/llie/zero_ig/zero_ig/pretrained/zero_ig_lol.pt"  # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 2                                                                 # Random seed.
imgsz       : &imgsz 512                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs 2000                                                      # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Optimizer
optimizer: &optimizer                                                           # Optimizer(s).
  lr          : 0.0003
  weight_decay: 0.0003
