# Basic
hostname    : ~
config      : ~
arch        : "srgb_tir"
model       : "srgb_tir"
data        : "gta_sthereo"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "srgb_tir_gta_sthereo"
save_dir    : ~
weights     : "zoo/vision/dtype/thermal/srgb_tir/srgb_tir/gta_sthereo/srgb_tir_gta_sthereo.pt"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 200
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
keep_subdirs: False
use_fullname: False
exist_ok    : True
verbose     : True

# Misc
a2b         : 0        # 1 for a2b and 0 for b2a
seed        : 1234     # random seed
num_style   : 30       # number of styles to sample
synchronized: True     # whether to use synchronized style code
output_only : True     # whether only save the output images or also save the input images
trainer     : "MUNIT"  # MUNIT|UNIT
