# Basic
root        : ~                                                                 # Root directory of the current run.
arch        : "lime"                                                            # Model architecture or family (e.g., resnet).
model       : &model "lime"                                                     # Model name (e.g., resnet50).
data        : &data ~                                                           # Dataset name (e.g., cifar10) or directory (e.g., data/cifar10).
fullname    : &fullname "lime"                                                  # Full name of the current run (e.g., resnet50_cifar10_01). If not set, it will be this file's name.
save_dir    : &save_dir ~                                                       # Saving directory. If not set, it will be `root/arch/model/data`.
weights     : &weights ~                                                        # Path to the pretrained weights.
device      : 0                                                                 # Running device (i.e., cuda:0 | cuda:0,1,2,3 | cpu).
seed        : 0                                                                 # Random seed.
imgsz       : &imgsz 512                                                        # Image size for the model.
resize      : False                                                             # Resize the input image to `imgsz`.
epochs      : &epochs ~                                                         # Training epochs.
steps       : &steps ~                                                          # Training steps.
benchmark   : False                                                             # Benchmark the model.
save_image  : True                                                              # Save the output image.
save_debug  : &save_debug True                                                  # Save the debug information.
use_fullname: True                                                              # Use the full name for the save_dir.
keep_subdirs: False                                                             # Keep subdirectories in the save_dir.
exist_ok    : True                                                              # If ``False``, it will delete the save directory if it already exists.
verbose     : &verbose True                                                     # Verbosity.

# Network
network: &network                                                               # Network architecture.
  gamma  : 0.6                                                                  # Gamma correction parameter
  lambda_: 0.15                                                                 # The weight for balancing the two terms in the illumination refinement optimization objective
  lime   : True                                                                 # Use the LIME method. By default, the DUAL method is used
  sigma  : 3                                                                    # Spatial standard deviation for spatial affinity based Gaussian weights
  bc     : 1                                                                    # Parameter for controlling the influence of Mertens's contrast measure
  bs     : 1                                                                    # Parameter for controlling the influence of Mertens's saturation measure
  be     : 1                                                                    # Parameter for controlling the influence of Mertens's well exposedness measure
  eps    : 0.01                                                                 # Constant to avoid computation instability
